spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test0110?characterEncoding=utf-8&useSSL=false
    username: root
    password: 520955lxy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /note


